version: '3.8'

services:
  # Apache + PHP Service
  web:
    image: php:8.2-apache
    container_name: vuestarter_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - vuestarter_network
    depends_on:
      - mariadb

  # MariaDB Service
  mariadb:
    image: mariadb:latest
    container_name: vuestarter_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - vuestarter_network

  # Adminer Service
  adminer:
    image: adminer:latest
    container_name: vuestarter_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - vuestarter_network
    depends_on:
      - mariadb

  # MailHog Service
  mailhog:
    image: mailhog/mailhog:latest
    container_name: vuestarter_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    networks:
      - vuestarter_network

networks:
  vuestarter_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
