version: '3.8'

services:
  # MariaDB Service
  mariadb:
    image: mariadb:latest
    container_name: vuestarter_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - vuestarter_network

  # Adminer Service
  adminer:
    image: adminer:latest
    container_name: vuestarter_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - vuestarter_network
    depends_on:
      - mariadb

  # MailHog Service
  mailhog:
    image: mailhog/mailhog:latest
    container_name: vuestarter_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    networks:
      - vuestarter_network

  # Matomo Service
  matomo:
    image: matomo:latest
    container_name: vuestarter_matomo
    restart: unless-stopped
    environment:
      MATOMO_DATABASE_HOST: mariadb
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: ${DB_USERNAME}
      MATOMO_DATABASE_PASSWORD: ${DB_PASSWORD}
      MATOMO_DATABASE_DBNAME: matomo
    ports:
      - "8090:80"
    volumes:
      - matomo_data:/var/www/html
    networks:
      - vuestarter_network
    depends_on:
      - mariadb

networks:
  vuestarter_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local